# Generated by Django 6.0.1 on 2026-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_usernoteprogress_usertaskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskprogress',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submissions/', verbose_name='Submission File'),
        ),
        migrations.AlterField(
            model_name='usertaskprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
    ]
